name: real_soft_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  mime: ^1.0.4
  image: ^3.0.2
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  get_it: ^7.2.0
  camera: ^0.10.5+6
  google_ml_kit: ^0.13.0
  fk_user_agent: ^2.1.0
  m_toast: ^0.2.0
  flutter_pdfview: ^1.3.2
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  flutter_typeahead: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/files/language.json
    - assets/files/uzbek.json
